### ISSUE TITLE
Offline support for Windows

### ISSUE THREAD

**Issue by xbowzone** [appu1232/guyamoe#114]
Any plans to make an app for Windows or a browser extension to read offline cbz/cbr manga?

**Comment by Algoinde** [comment]
Yeah, there are. First I wanted to rewrite the reader because I had run into a bit of technical debt - needs a better data structure, a bit of redesign maybe also port it to an actual framework. After that, yeah, it could be done. Was a bit low on time this year, but I plan to start on this next month.

**Comment by xbowzone** [comment]
Awesome!
