### ISSUE TITLE
Page selector overlay cannot be dismissed on mobile

### ISSUE THREAD

**Issue by DanielHZhang** [appu1232/guyamoe#6]
The overlay remains regardless of where you tap on the screen, which causes you to skip pages and makes navigating to the next page extremely frustrating.

Tapping on the overlay should dismiss it and allow you to continue reading normally.

Additionally, the majority of the navigation bar is positioned off-screen in the mobile reader.

![image](https://user-images.githubusercontent.com/30360288/71316729-0ac03980-2443-11ea-9f8a-3204477985c2.png)

This can be easily replicated in Chrome DevTools, and seems to occur for a variety of phone sizes.

![image](https://user-images.githubusercontent.com/30360288/71316815-d483b980-2444-11ea-8dff-ff471bf3614b.png)

**Comment by Algoinde** [comment]
Hi! Thank you for reporting.
I am aware of this issue and it's fixed in the reader overhaul that I'm trying to finish and push right now.
Workaround: turn your phone into landscape, open the sidebar, turn it back into portrait.
I'll see if I can do a hotfix for this, though, as the overhaul cannot be yet released.

**Comment by DanielHZhang** [comment]
I figured out the root cause: if you request desktop site on mobile, collapse the sidebar, and then stop requesting desktop site, the preview gets stuck. Was in the middle of making a PR but I'm stuck in the build process at the moment.

**Comment by Algoinde** [comment]
This was resolved in [eff19de](https://github.com/appu1232/guyamoe/commit/eff19dee997c37b2cae5b265d8c23f8eb90d287a).
