### ISSUE TITLE
BBCode is not parsed properly

### ISSUE THREAD

**Issue by DrWhoCares** [appu1232/guyamoe#88]
https://guya.moe/proxy/mangadex/36329/
The description, the bbcode is unparsed.

**Comment by funkyhippo** [comment]
That's intended behaviour since the proxy descriptions are all sanitized before rendering, so adding an exception for the MD proxy plus actual parsing of BBCode to HTML seems to be of low value.

I'd be open to the idea of parsing the description, but my gut tells me that most people end up using the proxy for the reader anyway, so they're unlikely going to pay attention to the raw description. I'll get back to you on that.

**Comment by DrWhoCares** [comment]
A short, simple solution is to just remove any BBCode tags.
