### ISSUE TITLE
Add Imgbox.com

### ISSUE THREAD

**Issue by Ever4engel** [appu1232/guyamoe#92]
support imgbox.com to be used cross your proxy like imgur 
here a test chapter: [OPM140](https://imgbox.com/omjEa6cB)

ps: Imgur does compression on anything larger than 1mb. Basically all colours & spreads which is less than ideal.
imgbox don't.

**Comment by Rapptz** [comment]
The gallery URL (e.g. https://imgbox.com/g/BvqOlpVY4e) might be better suited since it gives all the image URLs in a more workable manner.

**Comment by funkyhippo** [comment]
I wouldn't mind adding support for this, but it seems like their servers and CDN are based in Europe. From that album you linked, most of the images take ~3s to load. Can you confirm whether it's slow for you as well?

**Comment by Ever4engel** [comment]
on my side ? just a normal behavior,  i don't notice it's as slow as you say ^^
btw i'm from europe

**Comment by 68595959** [comment]
Hmm...

**Comment by Ever4engel** [comment]
> 
> 
> Hmm...

???

**Comment by 68595959** [comment]
...Disgrace... And the range of signal transmission does not always seem to affect the speed; can try to take a chance... I can't say anything else, my head hurts...

**Comment by Ever4engel** [comment]
should i close this? (if it's abandoned)

**Comment by Algoinde** [comment]
@funkyhippo we didn't hear anything from imgbox admins, right?

**Comment by funkyhippo** [comment]
No, but that was for imagechest.

Imgbox has relatively high latency on our host, so it wouldn't be a great experience. I'm fine with implementing it, though.

**Comment by funkyhippo** [comment]
Added. [Here's the cubari URL for your example gallery](https://cubari.moe/read/imgbox/BvqOlpVY4e/1/1/), which you can get from the `cubari.moe/imgbox/<gallery_id>` endpoint. Unfortunately, we can't cleanly map the normal prefix (`cubari.moe/g/<gallery_id>`) since nhentai uses the same scheme.

I'd like to keep this issue open for the next little bit in case you come across any broken images -- I'm not 100% certain I'm mapping the thumbnails to original image URLs correctly since I haven't seen enough examples to know. It works fine in my limited testing, though.

---

For anybody else stumbling across this issue, this means imgbox can also be used as a chapter image source now, which would save the hassle of manually grepping the image URLs to throw into the JSON array.

**Comment by funkyhippo** [comment]
I'll assume this is resolved since I didn't get any feedback on it. Feel free to re-open or make a new issue if you come across any issues.
