### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Ever4engel** [appu1232/guyamoe#93]
is it possible to get guya.moe's webreader template (if it's open source/freeware) ?

**Comment by Algoinde** [comment]
It is open source in this repo, but the website runs on django, a python framework. By your wording I assume you mean a WordPress template, so no, there is no such template.

**Comment by Ever4engel** [comment]
> 
> 
> It is open source in this repo, but the website runs on django, a python framework. By your wording I assume you mean a WordPress template, so no, there is no such template.

i meant the template not the website itself (like foolside, flat, madara... and so on)
i can get is from this repo ?

**Comment by Algoinde** [comment]
Foolslide is a PHP-based software, Madara is a WordPress theme, Flat Manga is a WordPress theme.
Our reader uses an entirely different codebase; we don't have a WordPress template/theme because it was never supposed to work with WordPress, it's built with a different CRM. You could use https://cubari.moe/ to link to chapters using imgur links displayed in this reader.

**Comment by Ever4engel** [comment]
i see thanks !
i'm not very familiar with webreaders stuffs

**Comment by ObserverOfTime** [comment]
Couldn't you potentially turn the reader into a JS library akin to xbreader?
